In [ ]:
import pandas as pd # Read CSV files, Filter row, Add columns, Analyze data
import numpy as np # mathematical lib,work with number, arrays, calculation

# machine learning model work with numbers
# many ML algo internally use NumPay
# Even Sciket-learn depends heavily on NumPy.

from sklearn.model_selection import train_test_split #-->  it divides data into : training data and testing data 
# WHY DO WE NEED IT 

# if we  have 10000 student data snd i train on all 10000 records, then how will i knoew that model is working correctly or not so 
# i split 80 for train and 20 for test


from sklearn.compose import ColumnTransformer
# COLUMN TRANSFORMER HELP US to " convert these text columns into number but level numericalcolumns uncharged ".


from sklearn.pipeline import Pipeline

# pipeline connect multiple  steps together

# WHY WE USE THIS
# clean code, less mistakes, used in real project
from sklearn.preprocessing import  OneHotEncoder
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    accuracy_score,
    classification_report, 
    confusion_matrix
)

In [ ]:
# example 
 
# numpay use in algo

#        np.mean (ranks) :---  Find average rank

#--------------------------------------------------------------------------------------------------------------------

# from sklearn.model_selection import train_test_split -------------->>>>>

In [6]:
! pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\asus\appdata\roaming\python\python314\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asus\appdata\roaming\python\python314\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
df = pd.read_csv("EAPCET_dataset.csv")

In [3]:
df.head()

,Inst Code,Institute Name,Place,Co Education,College Type,Branch Code,Branch Name,Closing_Rank,Category,Gender,...,Prev_Year_Closing_Rank,Opening_Rank,Branch_Demand,Institute_Difficulty,Category_Pressure,Normalized_Closing_Rank,No_of_qualifiers,Competitive_Percentile,NIRF_Rank,Institute_Tier
0,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CIV,CIVIL ENGINEERING,58226,OC,BOYS,...,58226,34935.6,102890.67220,73114.68182,57972.17897,0.378596,151779,61.64,Not Ranked,Tier 4
1,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE),28542,OC,BOYS,...,28542,17125.2,90618.74216,73114.68182,57972.17897,0.181427,151779,81.20,Not Ranked,Tier 4
2,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,23801,OC,BOYS,...,23801,14280.6,89064.17384,73114.68182,57972.17897,0.149936,151779,84.32,Not Ranked,Tier 4
3,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,22828,OC,BOYS,...,22828,13696.8,84415.78707,73114.68182,57972.17897,0.143473,151779,84.96,Not Ranked,Tier 4
4,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),32808,OC,BOYS,...,32808,19684.8,81686.20455,73114.68182,57972.17897,0.209763,151779,78.38,Not Ranked,Tier 4

In [ ]:
# Scikit-learn contains hundreds of machine learning tools.Scikit-learn contains hundreds of machine learning tools.

In [ ]:
# create a  Recommendation score

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # this is object from minmaxscaler class
df[[ # double brackit are used because multiple columns are involved
    
    "Branch_Demand_N",
    "Institute_Difficulty_N",
    "Competitive_Percentile_N" # selected multiple columns in a Pandas Data Frame
]] = scaler.fit_transform(df[[
    "Branch_Demand",
    "Institute_Difficulty",
    "Competitive_Percentile"
]])

df["Recommendation_Score"] = (
      0.5 * df["Branch_Demand_N"]
    + 0.3 * df["Institute_Difficulty_N"]
    + 0.2 * df["Competitive_Percentile_N"]
)

In [8]:
# select features

features = [
    "Institute Name",
    "Place",
    "College Type",
    "Branch Name",
    "Category",
    "Gender",
    "ROUND",
    "year",
    "Closing_Rank",
    "Prev_Year_Closing_Rank",
    "Opening_Rank",
    "Branch_Demand",
    "Institute_Difficulty",
    "Category_Pressure",
    "Normalized_Closing_Rank",
    "Competitive_Percentile",
    "NIRF_Rank",
    "Institute_Tier"
]

x = df[features]

y = df["Recommendation_Score"]

In [9]:
# separate Numerical and Categorical Features
categorical_features  = [
    "Institute Name",
    "Place",
    "College Type",
    "Branch Name",
    "Category",
    "Gender",
    "NIRF_Rank",
    "Institute_Tier"
]

numerical_features = [
    "ROUND",
    "year",
    "Closing_Rank",
    "Prev_Year_Closing_Rank",
    "Opening_Rank",
    "Branch_Demand",
    "Institute_Difficulty",
    "Category_Pressure",
    "Normalized_Closing_Rank",
    "Competitive_Percentile"
]

In [10]:
# preprocessing

preprossing = ColumnTransformer(
    transformers =[
        (
            "cat",
            OneHotEncoder(handle_unknown = "ignore"),
            categorical_features
        )
    ],
    remainder = "passthrough"
)

In [11]:
# Train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [12]:
# building pipeline

pipeline = Pipeline([
    ("preprocessing", preprossing),
    (
        "model",
        RandomForestRegressor(
            n_estimators=300,
            max_depth=15,
            random_state=42,
            n_jobs=-1
        )
    )
])

In [13]:
# tran_model

pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Institute Name', 'Place',
                                                   'College Type',
                                                   'Branch Name', 'Category',
                                                   'Gender', 'NIRF_Rank',
                                                   'Institute_Tier'])])),
                ('model',
                 RandomForestRegressor(max_depth=15, n_estimators=300,
                                       n_jobs=-1, random_state=42))])

In [14]:
# Get Recommendations


user_rank = 15000
user_category = "OC"
user_gender = "BOYS"
user_branch = "COMPUTER SCIENCE AND ENGINEERING"

In [15]:
# predict probability

eligible = df[
    (df["Category"] == user_category)
    &
    (df["Gender"] == user_gender)
    &
    (df["Branch Name"] == user_branch)
    &
    (df["Closing_Rank"] >= user_rank)
].copy()

In [16]:
# predict 

eligible["Predicted_Score"] = pipeline.predict(
    eligible[features]
)

In [ ]:
# print(df["Category"].unique())
# print(df["Gender"].unique())
# print(df["Branch Name"].unique()[:20])

['OC' 'BC_A' 'BC_B' 'BC_C' 'BC_D' 'BC_E' 'SC_I' 'SC_II' 'SC_III' 'ST'
 'EWS']
['BOYS' 'GIRLS']
['CIVIL ENGINEERING' 'COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE)'
 'COMPUTER SCIENCE AND ENGINEERING'
 'COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL INTELLIGENCE AND MACHINE \nLEARNING)'
 'COMPUTER SCIENCE AND ENGINEERING (IOT)'
 'ELECTRONICS AND COMMUNICATION \nENGINEERING'
 'ELECTRICAL AND ELECTRONICS ENGINEERING' 'INFORMATION TECHNOLOGY'
 'MECHANICAL ENGINEERING' 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING'
 'MINING ENGINEERING' 'ARTIFICIAL INTELLIGENCE'
 'COMPUTER SCIENCE AND ENGINEERING (CYBER \nSECURITY)'
 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE'
 'COMPUTER ENGINEERING(SOFTWARE \nENGINEERING)'
 'COMPUTER SCIENCE AND BUSINESS SYSTEM' 'BIO-MEDICAL ENGINEERING'
 'CHEMICAL ENGINEERING' 'PHARMACEUTICAL ENGINEERING'
 'AGRICULTURAL ENGINEERING']

In [17]:
recommendations = eligible.sort_values(
    "Predicted_Score",
    ascending=False
)

In [18]:

recommendations[
    [
        "Institute Name",
        "Branch Name",
        "Place",
        "Closing_Rank",
        "Predicted_Score"
    ]
].head(1)

,Institute Name,Branch Name,Place,Closing_Rank,Predicted_Score
20414,VAAGDEVI COLLEGE OF ENGINEERING \n(AUTONOMOUS),COMPUTER SCIENCE AND ENGINEERING,WARANGAL,54553,0.757257

In [19]:
# above code i giving duplicate and multiple time same college name so to get prevent from this i will do

final_recommendations = (
    recommendations
    .groupby(
        [
            "Institute Name",
            "Branch Name",
            "Place"
        ],
        as_index=False
    )
    .agg({
        "Closing_Rank": "max",
        "Predicted_Score": "max"
    })
    .sort_values(
        "Predicted_Score",
        ascending=False
    )
)

final_recommendations.head()

,Institute Name,Branch Name,Place,Closing_Rank,Predicted_Score
100,VAAGDEVI COLLEGE OF ENGINEERING \n(AUTONOMOUS),COMPUTER SCIENCE AND ENGINEERING,WARANGAL,54553,0.757257
97,UNIVERSITY COLLEGE OF ENGINEERING \nNIZAMABAD,COMPUTER SCIENCE AND ENGINEERING,NIZAMABAD,70854,0.753230
66,NALLAMALLA REDDY ENGINEERING COLLEGE \n(AUTONO...,COMPUTER SCIENCE AND ENGINEERING,GHATKESAR,32439,0.749293
37,JNTUH UNIVERSITY COLLEGE OF \nENGINEERING RAJA...,COMPUTER SCIENCE AND ENGINEERING,SIRCILLA\nAGRAHARAM \nRAJANNA,27854,0.748688
5,AURORAS SCIENTIFIC AND TECHNOLOGICAL \nINSTITUTE,COMPUTER SCIENCE AND ENGINEERING,GHATKESAR,31381,0.743089

In [20]:
eligible["Rank_Match"] = (
    user_rank / eligible["Closing_Rank"]
)

In [21]:
eligible["Rank_Match"] = eligible["Rank_Match"].clip(upper=1)

In [22]:
from sklearn.metrics import r2_score, mean_absolute_error

predictions = pipeline.predict(x_test)

print("R2 Score:", r2_score(y_test, predictions))
print("MAE:, mean_absolute_error(y_test, predictions)")

R2 Score: 0.9997561628215422
MAE:, mean_absolute_error(y_test, predictions)

In [23]:
# show recommendations

recommendation = eligible.sort_values(
    "Recommendation_Score",
    ascending=False
)

recommendation.head(1)

,Inst Code,Institute Name,Place,Co Education,College Type,Branch Code,Branch Name,Closing_Rank,Category,Gender,...,No_of_qualifiers,Competitive_Percentile,NIRF_Rank,Institute_Tier,Branch_Demand_N,Institute_Difficulty_N,Competitive_Percentile_N,Recommendation_Score,Predicted_Score,Rank_Match
20414,VAGE,VAAGDEVI COLLEGE OF ENGINEERING \n(AUTONOMOUS),WARANGAL,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,54553,OC,BOYS,...,151779,64.06,Not Ranked,Tier 4,0.692743,0.941552,0.645831,0.758004,0.757257,0.274962

In [24]:
# user input section

user_rank = 25000
user_category = "OC"
user_gender = "BOYS"
user_branch = "COMPUTER SCIENCE AND ENGINNERING"

In [25]:
recommendation.head(1)

,Inst Code,Institute Name,Place,Co Education,College Type,Branch Code,Branch Name,Closing_Rank,Category,Gender,...,No_of_qualifiers,Competitive_Percentile,NIRF_Rank,Institute_Tier,Branch_Demand_N,Institute_Difficulty_N,Competitive_Percentile_N,Recommendation_Score,Predicted_Score,Rank_Match
20414,VAGE,VAAGDEVI COLLEGE OF ENGINEERING \n(AUTONOMOUS),WARANGAL,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,54553,OC,BOYS,...,151779,64.06,Not Ranked,Tier 4,0.692743,0.941552,0.645831,0.758004,0.757257,0.274962

In [26]:
# which colum have what value

print(df["Category"].unique())
print(df["Gender"].unique())
print(df["Branch Name"].unique()[:20])

['OC' 'BC_A' 'BC_B' 'BC_C' 'BC_D' 'BC_E' 'SC_I' 'SC_II' 'SC_III' 'ST'
 'EWS']
['BOYS' 'GIRLS']
['CIVIL ENGINEERING' 'COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE)'
 'COMPUTER SCIENCE AND ENGINEERING'
 'COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL INTELLIGENCE AND MACHINE \nLEARNING)'
 'COMPUTER SCIENCE AND ENGINEERING (IOT)'
 'ELECTRONICS AND COMMUNICATION \nENGINEERING'
 'ELECTRICAL AND ELECTRONICS ENGINEERING' 'INFORMATION TECHNOLOGY'
 'MECHANICAL ENGINEERING' 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING'
 'MINING ENGINEERING' 'ARTIFICIAL INTELLIGENCE'
 'COMPUTER SCIENCE AND ENGINEERING (CYBER \nSECURITY)'
 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE'
 'COMPUTER ENGINEERING(SOFTWARE \nENGINEERING)'
 'COMPUTER SCIENCE AND BUSINESS SYSTEM' 'BIO-MEDICAL ENGINEERING'
 'CHEMICAL ENGINEERING' 'PHARMACEUTICAL ENGINEERING'
 'AGRICULTURAL ENGINEERING']

In [27]:
# evaluate the model

# Q  :--- why add this line 

# because every ML should answer: how well does the model perform?

from sklearn.metrics import r2_score, mean_absolute_error

predictions = pipeline.predict(x_test)

print("R2 Score:", r2_score(y_test, predictions))
print("MAE:", mean_absolute_error(y_test, predictions))

R2 Score: 0.9997561628215422
MAE: 0.0007563701032520726

In [28]:
# save the model

# beacuse traning model should be saved and reuse

import joblib
joblib.dump(
    pipeline,
    "college_recommendation_model.pkl"
)

['college_recommendation_model.pkl']

In [29]:
# create a final user input

# this make the notbook interactive

user_rank = 30000
user_category = "OC"
user_gender = "Boys"
user_branch = "COMPUTER SCIENCE AND ENGINEERING"

In [30]:
# Display recommendation nicely

# insted of this
#       recommendation.head(10)

# i use


#----------------------------------------------------------------------------------------------------------------------------------

# final_output = recommendations[
#     [
#          "Institute Name",
#         "Branch Name",
#         "Place",
#         "Closing_Rank",
#         "Predicted_Score"
#     ]
#     ].head(10)

#display(final_output)


#THIS CODE GIVE THE DUPLICATE VALUE IN OUT SO TO GET PRECVENTION FROM THIS I DO


final_output = (
    recommendations
    .groupby(
        ["Institute Name", "Branch Name", "Place"],
        as_index=False
    )
    .agg({
        "Closing_Rank": "max",
        "Predicted_Score": "max"
    })
    .sort_values(
        "Predicted_Score",
        ascending=False
    )
)
display(final_output)

# NOW THIS CODE WILL GIVE ONE RPOW PER COLLEGE

,Institute Name,Branch Name,Place,Closing_Rank,Predicted_Score
100,VAAGDEVI COLLEGE OF ENGINEERING \n(AUTONOMOUS),COMPUTER SCIENCE AND ENGINEERING,WARANGAL,54553,0.757257
97,UNIVERSITY COLLEGE OF ENGINEERING \nNIZAMABAD,COMPUTER SCIENCE AND ENGINEERING,NIZAMABAD,70854,0.753230
66,NALLAMALLA REDDY ENGINEERING COLLEGE \n(AUTONO...,COMPUTER SCIENCE AND ENGINEERING,GHATKESAR,32439,0.749293
37,JNTUH UNIVERSITY COLLEGE OF \nENGINEERING RAJA...,COMPUTER SCIENCE AND ENGINEERING,SIRCILLA\nAGRAHARAM \nRAJANNA,27854,0.748688
5,AURORAS SCIENTIFIC AND TECHNOLOGICAL \nINSTITUTE,COMPUTER SCIENCE AND ENGINEERING,GHATKESAR,31381,0.743089
...,...,...,...,...,...
95,TRINITY COLLEGE OF ENGINEERING AND \nTECHNOLOGY,COMPUTER SCIENCE AND ENGINEERING,KARIMNAGAR,123054,0.624657
16,CMR INSTITUTE OF TECHNOLOGY \n(AUTONOMOUS),COMPUTER SCIENCE AND ENGINEERING,KANDLAKOYA,22227,0.624052
24,GOKARAJU LAILAVATHI ENGINEERING \nCOLLEGE,COMPUTER SCIENCE AND ENGINEERING,BACHUPALLY,17939,0.622401
22,GATE INSTITUTE OF TECHNOLOGYAND \nSCIENCES,COMPUTER SCIENCE AND ENGINEERING,KODAD,82036,0.614390
46,KESHAV MEMORIAL ENGINEERING COLLEGE,COMPUTER SCIENCE AND ENGINEERING,KACHWANISING\nARAM,17041,0.611199

In [31]:
def recommend_colleges(rank, category, gender, branch):

    # Filter eligible colleges
    eligible = df[
        (df["Category"] == category)
        &
        (df["Gender"] == gender)
        &
        (df["Branch Name"] == branch)
        &
        (df["Closing_Rank"] >= rank)
    ].copy()

    # Check if colleges found
    if len(eligible) == 0:
        print("No colleges found for given criteria")
        return

    # Predict recommendation score
    eligible["Predicted_Score"] = pipeline.predict(
        eligible[features]
    )

    # Calculate rank difference
    eligible["Rank_Difference"] = (
        eligible["Closing_Rank"] - rank
    )

    # Remove duplicates and keep best score
    final_output = (
        eligible
        .groupby(
            [
                "Institute Name",
                "Branch Name",
                "Place"
            ],
            as_index=False
        )
        .agg({
            "Closing_Rank": "max",
            "Predicted_Score": "max",
            "Rank_Difference": "min"
        })
        .sort_values(
            "Predicted_Score",
            ascending=False
        )
    )

    # Display top 10
    return final_output[
        [
            "Institute Name",
            "Branch Name",
            "Place",
            "Closing_Rank",
            "Rank_Difference",
            "Predicted_Score"
        ]
    ].head(10)

In [32]:
recommend_colleges(
    rank=30000,
    category="OC",
    gender="BOYS",
    branch="COMPUTER SCIENCE AND ENGINEERING"
)

,Institute Name,Branch Name,Place,Closing_Rank,Rank_Difference,Predicted_Score
78,VAAGDEVI COLLEGE OF ENGINEERING \n(AUTONOMOUS),COMPUTER SCIENCE AND ENGINEERING,WARANGAL,54553,24553,0.757257
75,UNIVERSITY COLLEGE OF ENGINEERING \nNIZAMABAD,COMPUTER SCIENCE AND ENGINEERING,NIZAMABAD,70854,40854,0.753230
46,NALLAMALLA REDDY ENGINEERING COLLEGE \n(AUTONO...,COMPUTER SCIENCE AND ENGINEERING,GHATKESAR,32439,2439,0.749293
4,AURORAS SCIENTIFIC AND TECHNOLOGICAL \nINSTITUTE,COMPUTER SCIENCE AND ENGINEERING,GHATKESAR,31381,1381,0.743089
0,ABDULKALAM INST OF TECHNOLOGY AND \nSCI,COMPUTER SCIENCE AND ENGINEERING,KOTHAGUDEM,55273,25273,0.735595
21,HOLY MARY INSTITUTE OF TECH SCIENCE \n(AUTONOM...,COMPUTER SCIENCE AND ENGINEERING,KEESARA,56289,26289,0.735187
51,SAMSKRUTHI COLLEGE OF ENGG AND \nTECHNOLOGY (A...,COMPUTER SCIENCE AND ENGINEERING,GHATKESAR,53842,23842,0.732475
19,GLOBAL INST OF ENGINEERING AND \nTECHNOLOGY (A...,COMPUTER SCIENCE AND ENGINEERING,CHILKUR,65377,35377,0.729736
76,UNIVERSITY COLLEGE OF ENGINEERING \nPALAMURU U...,COMPUTER SCIENCE AND ENGINEERING,MAHABUBNAGA\nR,44923,14923,0.728987
36,KOTHAGUDEM)\nEARTH SCIENCES UNIV OF TELANGANA ...,COMPUTER SCIENCE AND ENGINEERING,KOTHAGUDEM,60997,30997,0.728882

In [33]:
recommendation.head(1)

,Inst Code,Institute Name,Place,Co Education,College Type,Branch Code,Branch Name,Closing_Rank,Category,Gender,...,No_of_qualifiers,Competitive_Percentile,NIRF_Rank,Institute_Tier,Branch_Demand_N,Institute_Difficulty_N,Competitive_Percentile_N,Recommendation_Score,Predicted_Score,Rank_Match
20414,VAGE,VAAGDEVI COLLEGE OF ENGINEERING \n(AUTONOMOUS),WARANGAL,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,54553,OC,BOYS,...,151779,64.06,Not Ranked,Tier 4,0.692743,0.941552,0.645831,0.758004,0.757257,0.274962

In [ ]:
# from here i will do 


# Try different machine learning models
# Compare Random Forest with XGBoost, LightGBM, or CatBoost to check if accuracy improves.

In [32]:
! pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\asus\appdata\roaming\python\python314\site-packages (from xgboost) (2.4.3)
Requirement already satisfied: scipy in c:\users\asus\appdata\roaming\python\python314\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
    --------------------------------------- 1.6/69.5 MB 8.2 MB/s eta 0:00:09
   -- ------------------------------------- 3.7/69.5 MB 8.6 MB/s eta 0:00:08
   --- ------------------------------------ 5.5/69.5 MB 9.0 MB/s eta 0:00:08
   ---- ----------------------------------- 7.3/69.5 MB 9.0 MB/s eta 0:00:07
   ----- ---------------------------------- 9.2/69.5 MB 8.9 MB/s eta 0:00:07
   ------ --------------------------------- 11.0/69.5 MB 9.0 MB/s eta 0:00:07
   ------- -------------------------------- 12.8/69.5 MB 8.9 MB/s eta 0:00:07
   -------- ------------------------------- 14.9/69.5 MB 8.9 MB/s eta 0:00:07
   --------- ------------------------------ 16.8/69.5 MB 9.0 MB/s eta 0:00:06
   ---------- ----------------------------- 18.6/69.5 MB 8.9 MB/s eta 0:00:06
   ----------- ---------------------------- 20.4/69.5 MB 8.9 MB/s eta 0:00:06
   ------------ --------------------------- 22.3/69.5 MB 8.9 MB/s eta 0:00:06
   ------------- -------------------------- 23.9/69.5 MB 8.8 MB/s eta 0:00:06
   -------------- ------------------------- 25.4/69.5 MB 8.7 MB/s eta 0:00:06
   --------------- ------------------------ 27.3/69.5 MB 8.7 MB/s eta 0:00:05
   ---------------- ----------------------- 28.8/69.5 MB 8.7 MB/s eta 0:00:05
   ----------------- ---------------------- 30.7/69.5 MB 8.7 MB/s eta 0:00:05
   ------------------ --------------------- 32.5/69.5 MB 8.7 MB/s eta 0:00:05
   ------------------- -------------------- 34.6/69.5 MB 8.7 MB/s eta 0:00:04
   -------------------- ------------------- 36.2/69.5 MB 8.7 MB/s eta 0:00:04
   --------------------- ------------------ 38.0/69.5 MB 8.7 MB/s eta 0:00:04
   ----------------------- ---------------- 40.1/69.5 MB 8.8 MB/s eta 0:00:04
   ------------------------ --------------- 41.9/69.5 MB 8.8 MB/s eta 0:00:04
   ------------------------- -------------- 43.8/69.5 MB 8.8 MB/s eta 0:00:03
   -------------------------- ------------- 45.6/69.5 MB 8.8 MB/s eta 0:00:03
   --------------------------- ------------ 47.4/69.5 MB 8.8 MB/s eta 0:00:03
   ---------------------------- ----------- 49.3/69.5 MB 8.8 MB/s eta 0:00:03
   ----------------------------- ---------- 51.4/69.5 MB 8.8 MB/s eta 0:00:03
   ------------------------------ --------- 53.2/69.5 MB 8.8 MB/s eta 0:00:02
   ------------------------------- -------- 55.1/69.5 MB 8.8 MB/s eta 0:00:02
   -------------------------------- ------- 56.6/69.5 MB 8.8 MB/s eta 0:00:02
   --------------------------------- ------ 58.5/69.5 MB 8.8 MB/s eta 0:00:02
   ---------------------------------- ----- 60.0/69.5 MB 8.8 MB/s eta 0:00:02
   ----------------------------------- ---- 61.9/69.5 MB 8.8 MB/s eta 0:00:01
   ------------------------------------ --- 63.7/69.5 MB 8.8 MB/s eta 0:00:01
   ------------------------------------- -- 65.8/69.5 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------  67.9/69.5 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 8.7 MB/s  0:00:07
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
! pip install catboost

Defaulting to user installation because normal site-packages is not writeable
Collecting catboost
  Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib (from catboost)
  Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from catboost) (2.4.3)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\asus\appdata\roaming\python\python314\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\asus\appdata\roaming\python\python314\site-packages (from catboost) (1.17.1)
Collecting plotly (from catboost)
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: six in c:\users\asus\appdata\roaming\python\python314\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas<4.0,>=0.24->catboost) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Collecting contourpy>=1.0.1 (from matplotlib->catboost)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->catboost)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->catboost)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->catboost)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=9 in c:\users\asus\appdata\roaming\python\python314\site-packages (from matplotlib->catboost) (12.1.1)
Collecting pyparsing>=3 (from matplotlib->catboost)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\asus\appdata\roaming\python\python314\site-packages (from plotly->catboost) (2.18.1)
Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 1.3/101.7 MB 7.1 MB/s eta 0:00:15
   - -------------------------------------- 3.1/101.7 MB 7.6 MB/s eta 0:00:14
   - -------------------------------------- 4.7/101.7 MB 7.7 MB/s eta 0:00:13
   -- ------------------------------------- 6.6/101.7 MB 8.0 MB/s eta 0:00:12
   --- ------------------------------------ 8.4/101.7 MB 8.3 MB/s eta 0:00:12
   ---- ----------------------------------- 10.5/101.7 MB 8.5 MB/s eta 0:00:11
   ---- ----------------------------------- 12.3/101.7 MB 8.5 MB/s eta 0:00:11
   ----- ---------------------------------- 14.2/101.7 MB 8.6 MB/s eta 0:00:11
   ------ --------------------------------- 16.3/101.7 MB 8.6 MB/s eta 0:00:10
   ------- -------------------------------- 18.1/101.7 MB 8.7 MB/s eta 0:00:10
   ------- -------------------------------- 19.9/101.7 MB 8.7 MB/s eta 0:00:10
   -------- ------------------------------- 21.8/101.7 MB 8.6 MB/s eta 0:00:10
   --------- ------------------------------ 23.3/101.7 MB 8.6 MB/s eta 0:00:10
   --------- ------------------------------ 25.4/101.7 MB 8.7 MB/s eta 0:00:09
   ---------- ----------------------------- 27.3/101.7 MB 8.7 MB/s eta 0:00:09
   ----------- ---------------------------- 29.1/101.7 MB 8.7 MB/s eta 0:00:09
   ------------ --------------------------- 31.2/101.7 MB 8.7 MB/s eta 0:00:09
   ------------ --------------------------- 33.0/101.7 MB 8.7 MB/s eta 0:00:08
   ------------- -------------------------- 34.9/101.7 MB 8.8 MB/s eta 0:00:08
   -------------- ------------------------- 36.7/101.7 MB 8.8 MB/s eta 0:00:08
   -------------- ------------------------- 38.0/101.7 MB 8.7 MB/s eta 0:00:08
   --------------- ------------------------ 39.8/101.7 MB 8.7 MB/s eta 0:00:08
   ---------------- ----------------------- 41.7/101.7 MB 8.7 MB/s eta 0:00:07
   ----------------- ---------------------- 43.5/101.7 MB 8.7 MB/s eta 0:00:07
   ----------------- ---------------------- 45.4/101.7 MB 8.7 MB/s eta 0:00:07
   ------------------ --------------------- 47.2/101.7 MB 8.6 MB/s eta 0:00:07
   ------------------- -------------------- 49.0/101.7 MB 8.7 MB/s eta 0:00:07
   ------------------- -------------------- 50.9/101.7 MB 8.7 MB/s eta 0:00:06
   -------------------- ------------------- 52.7/101.7 MB 8.7 MB/s eta 0:00:06
   --------------------- ------------------ 54.5/101.7 MB 8.7 MB/s eta 0:00:06
   ---------------------- ----------------- 56.4/101.7 MB 8.7 MB/s eta 0:00:06
   ---------------------- ----------------- 58.2/101.7 MB 8.7 MB/s eta 0:00:06
   ----------------------- ---------------- 60.3/101.7 MB 8.7 MB/s eta 0:00:05
   ------------------------ --------------- 61.9/101.7 MB 8.7 MB/s eta 0:00:05
   ------------------------- -------------- 64.0/101.7 MB 8.7 MB/s eta 0:00:05
   ------------------------- -------------- 65.5/101.7 MB 8.7 MB/s eta 0:00:05
   -------------------------- ------------- 67.4/101.7 MB 8.7 MB/s eta 0:00:04
   --------------------------- ------------ 69.2/101.7 MB 8.7 MB/s eta 0:00:04
   ---------------------------- ----------- 71.3/101.7 MB 8.7 MB/s eta 0:00:04
   ---------------------------- ----------- 73.1/101.7 MB 8.7 MB/s eta 0:00:04
   ----------------------------- ---------- 75.0/101.7 MB 8.7 MB/s eta 0:00:04
   ------------------------------ --------- 76.8/101.7 MB 8.7 MB/s eta 0:00:03
   ------------------------------ --------- 78.6/101.7 MB 8.7 MB/s eta 0:00:03
   ------------------------------- -------- 80.5/101.7 MB 8.7 MB/s eta 0:00:03
   -------------------------------- ------- 82.1/101.7 MB 8.7 MB/s eta 0:00:03
   --------------------------------- ------ 84.1/101.7 MB 8.7 MB/s eta 0:00:03
   --------------------------------- ------ 86.0/101.7 MB 8.7 MB/s eta 0:00:02
   ---------------------------------- ----- 87.8/101.7 MB 8.7 MB/s eta 0:00:02
   ----------------------------------- ---- 89.9/101.7 MB 8.7 MB/s eta 0:00:02
   ------------------------------------ --- 91.8/101.7 MB 8.7 MB/s eta 0:00:02
   ------------------------------------ --- 93.6/101.7 MB 8.7 MB/s eta 0:00:01
   ------------------------------------- -- 95.4/101.7 MB 8.7 MB/s eta 0:00:01
   -------------------------------------- - 97.3/101.7 MB 8.7 MB/s eta 0:00:01
   -------------------------------------- - 99.1/101.7 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  100.9/101.7 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 8.6 MB/s  0:00:11
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.5 MB 9.1 MB/s eta 0:00:01
   --------------- ------------------------ 3.7/9.5 MB 9.3 MB/s eta 0:00:01
   ----------------------- ---------------- 5.5/9.5 MB 9.3 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.5 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 9.0 MB/s  0:00:01
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ------------------------------- -------- 1.8/2.3 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 8.1 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading plotly-6.8.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.9 MB 9.2 MB/s eta 0:00:01
   -------------- ------------------------- 3.7/9.9 MB 9.0 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.9 MB 9.1 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 9.1 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 8.9 MB/s  0:00:01
Installing collected packages: pyparsing, plotly, kiwisolver, graphviz, fonttools, cycler, contourpy, matplotlib, catboost

   ---------------------------------------- 0/9 [pyparsing]
   ---------------------------------------- 0/9 [pyparsing]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ---- ----------------------------------- 1/9 [plotly]
   ------------- -------------------------- 3/9 [graphviz]
   ------------- -------------------------- 3/9 [graphviz]
   ------------- -------------------------- 3/9 [graphviz]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   ----------------- ---------------------- 4/9 [fonttools]
   -------------------------- ------------- 6/9 [contourpy]
   -------------------------- ------------- 6/9 [contourpy]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]
   ------------------------------- -------- 7/9 [matplotlib]

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
! pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Collecting lightgbm
  Using cached lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from lightgbm) (2.4.3)
Requirement already satisfied: scipy in c:\users\asus\appdata\roaming\python\python314\site-packages (from lightgbm) (1.17.1)
Using cached lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:



from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

from sklearn.ensemble import(
    RandomForestRegressor,
    GradientBoostingRegressor
)

In [39]:
models = {
    
    "Random Forest": RandomForestRegressor(
        n_estimators = 300,
        random_state = 42
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        random_state = 42
    ),

    "XGBoost": XGBRegressor(
        random_state = 42,
        verbose = 0
    ),

    "CatBoot": CatBoostRegressor(
        random_state = 42,
        verbose = 0
    ),

    "LightGBM": LGBMRegressor(
        random_state = 42
    )
}

In [41]:
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

results = []

for name, model in models.items():
    
    pipe = Pipeline([
        ("preprossing", preprossing),
        ("model", model)
    ])

    pipe.fit(x_train, y_train)

    predictions_1 = pipe.predict(x_test)
    results.append({
        "Model": name,

        "R2 Score": r2_score(
            y_test,
            predictions_1
        ),

        "MAE": mean_absolute_error(
            y_test,
            predictions_1
        ),

        "MSE": mean_squared_error(
            y_test,
            predictions_1
        )
    })

    results = pd.DataFrame(results)

    results.sort_values(
        "R2_score",
        ascending = False
    )

KeyError: 'R2_score'

In [ ]:
# We compared multiple regression algorithms, including Random Forest, Gradient Boosting, XGBoost, CatBoost, and LightGBM. Each model was trained using the same features and train-test split. Performance was evaluated using R² Score, Mean Absolute Error (MAE), and Mean Squared Error (MSE). The model with the highest R² Score and lowest error metrics was selected for the final recommendation system.